# Music Tagger Configuration

# 全局设置
global:
  min_confidence: 50  # 最小置信度阈值，低于此值的匹配将被忽略
  require_confirmation: true  # 是否需要用户确认匹配结果

# MusicBrainz 数据源设置
musicbrainz:
  enabled: true  # 是否启用 MusicBrainz 数据源
  app_name: "MusicTagger"  # 应用名称
  version: "1.0"  # 应用版本
  contact: "your@email.com"  # 联系邮箱
  weight: 1.0  # 搜索结果权重

# Spotify 数据源设置
spotify:
  enabled: false  # 是否启用 Spotify 数据源
  client_id: ""  # Spotify API Client ID
  client_secret: ""  # Spotify API Client Secret
  weight: 1.0  # 搜索结果权重

# 网易云音乐数据源设置
netease:
  enabled: false  # 是否启用网易云音乐数据源
  api_key: ""     # API密钥
  api_secret: ""  # API密钥密文
  weight: 1.0     # 搜索结果权重
  # 可选设置
  use_cache: true        # 是否缓存搜索结果
  cache_timeout: 86400   # 缓存超时时间（秒）

# QQ音乐数据源设置
qqmusic:
  enabled: false  # 是否启用QQ音乐数据源
  api_key: ""     # API密钥（如果需要）
  weight: 1.0     # 搜索结果权重
  # 可选设置
  use_cache: true        # 是否缓存搜索结果
  cache_timeout: 86400   # 缓存超时时间（秒）
